 ° ± ² ³ ´ µ ¶ · ¸ ¹ º » ¼ ½ ¾ ¿ À Á Â Ã Ä Å Æ Ç È É Ê Ë Ì Í Î Ï Ğ Ñ Ò Ó Ô Õ Ö × Ø Ù Ú Û Ü İ Ş ß 
10 
 7fÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´ 74Customization7f ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ70¿10
 7f³70                                                                            ³10
 7f³70       This is the customization screen. You entered by pressing F2         ³10
 7f³70                                                                            ³10
 7f³70                 Press any key to return to main screen                     ³10
 7f³70                                                                            ³10
 7f³70  You can add menu entries to the main screen and modify the corresponding  ³10
 7f³70  command lines. To do that you do not need to run a command but just to    ³10
 7f³70  edit the file /boot/efi/EFI/Slint/elilo.conf                              ³10
 7f³70                                                                            ³10
 7f³70  You will find detailed instructions in /usr/doc/elilo-<version>/elilo.txt ³10
 7f³70  (see under III/ Configuration file).                                      ³10
 7f³70                                                                            ³10
 7f³70  A word of caution: there is no simple way to test your changes and a      ³10
 7f³70  small mistake could render the boot menu unusable. To avoid that, always  ³10
 7f³70  keep at least one existing image section as is and duplicate if need be   ³10
 7f³70  even to modify it sligthly - but change the label! Then, check that you   ³10
 7f³70  can boot all new images sections before removing obsolete ones.           ³10
 7f³70  Also, only add, remove or changes Images sections unless you really know  ³10
 7f³70  what you are doing.                                                       ³10
 7f³70                                                                            ³10
 7f³70                                                                            ³10
 7fÀ70ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ10
