 ° ± ² ³ ´ µ ¶ · ¸ ¹ º » ¼ ½ ¾ ¿ À Á Â Ã Ä Å Æ Ç È É Ê Ë Ì Í Î Ï Ğ Ñ Ò Ó Ô Õ Ö × Ø Ù Ú Û Ü İ Ş ß 
10 
 7fÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´ 74Help Screen7f ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ70¿10
 7f³70                                                                            ³10
 7f³70            This is the help screen. You entered by pressing F1             ³10
 7f³70                                                                            ³10
 7f³70                   Press any key to return to main screen                   ³10
 7f³70                                                                            ³10
 7f³70  If you need to append kernel parameters to the command line to boot your  ³10
 7f³70  your system you can type them in the main menu, and edit a configuration  ³10
 7f³70  file to have them included by default.                                    ³10
 7f³70                                                                            ³10
 7f³70  You need to append kernel parameters and do not use an US keyboard? Don't ³10
 7f³70  panic! To find the key you need to press to print some character, search  ³10
 7f³70  KB_United_States.svg on the Internet.                                     ³10
 7f³70                                                                            ³10
 7f³70  You can customize the elilo boot menu after installation, to permanently  ³10
 7f³70  include kernel parameters in the command line, or to add  boot entries    ³10
 7f³70  to the main screen, for other kernels or other systems: go back to the    ³10
 7f³70  main screen then press F2 for more information.                           ³10
 7f³70                                                                            ³10
 7f³70                                                                            ³10
 7fÀ70ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ10
