 ° ± ² ³ ´ µ ¶ · ¸ ¹ º » ¼ ½ ¾ ¿ À Á Â Ã Ä Å Æ Ç È É Ê Ë Ì Í Î Ï Ğ Ñ Ò Ó Ô Õ Ö × Ø Ù Ú Û Ü İ Ş ß 
10
 7fÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´ 74Elilo boot manager menu7f ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ70¿10
 7f³70                                                                            ³10
 7f³70 From here you can boot your systems.                                       ³10
 7f³70                                                                            ³10
 7f³70 Select an OS to boot with the arrow keys, enter extra parameters at the    ³10
 7f³70 prompt if need be and press [Enter] to boot.                               ³10
 7f³70                                                                            ³10
 7f³70 On a serial console, use Ctrl-F followed by the relevant function key.     ³10
 7f³70                                                                            ³10
 7f³70 7eYou can get help pressing F1 and know how to customize this screen         70³10
 7f³70 7epressing F2. Then press any key to go back to this screen.                 70³10
 7f³70                                                                            ³10
 7f³70            ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ7f¿70              ³10
 7f³70            ³70          This is where the menu goes           7f³70             ³10
 7f³70            ³701e               (active colour)                  7f³70              ³10
 7f³70            ³70              (inactive colour)                 7f³70              ³10
 7f³70            ³70                                                1e7f³70             ³10
 7f³70            À7fÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ70              ³10
 7f³70                                                                            ³10
 7f³70 Extra parameters: 35                                                     70    ³10
 7f³70                                                                            ³10
 7f³70 [71F170-help]  [71F270-Customization]                                              ³10
 7fÀ70ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ10
